// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx01WaMankM-i2ZQdWYG5_FFt20QBzgt0',
    appId: '1:67811140524:android:75b19d6faea211a4a99009',
    messagingSenderId: '67811140524',
    projectId: 'goal-tracker-ec117',
    storageBucket: 'goal-tracker-ec117.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8DL6dGKj5lK9muwK-1n6Krp0vFQwduc',
    appId: '1:67811140524:ios:56f416a4a54806c5a99009',
    messagingSenderId: '67811140524',
    projectId: 'goal-tracker-ec117',
    storageBucket: 'goal-tracker-ec117.firebasestorage.app',
    iosBundleId: 'com.example.goalTracker',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASLXeuAFnVUPQAjJJGBTTBITUy_sCkWLQ',
    appId: '1:67811140524:web:a1186fa0ecaf8e74a99009',
    messagingSenderId: '67811140524',
    projectId: 'goal-tracker-ec117',
    authDomain: 'goal-tracker-ec117.firebaseapp.com',
    storageBucket: 'goal-tracker-ec117.firebasestorage.app',
    measurementId: 'G-LZ4SWMGZDP',
  );
}
